eg/tauts: swap derive order
ghc-9.0 failed with:

eg/tauts.hs:7:1: error: No instance for (Listable Name) arising from a use of ‘cons1’
7 | deriveListable ''Prop

c.f.: https://travis-ci.org/github/rudymatela/speculate/jobs/766812981#L625

This patch swaps the order of the two deriveListable calls
so that the Name instance is available before deriving Prop.

I wonder if this is a bug in GHC:
if I have two mutually recursive types
will I be able to derive an instance for them?